name: CI/CD Hello World Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build & push image
      run: |
        IMAGE=ginilekshmiao/hello-world-web:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    # Step 4: Deploy to DEV
    - name: Deploy to DEV
      run: |
        kubectl apply -k k8s/dev
        kubectl rollout status deployment/hello-world -n dev

    # Step 5: Deploy to QA if DEV succeeds
    - name: Deploy to QA
      run: |
        kubectl apply -k k8s/qa
        kubectl rollout status deployment/hello-world -n qa
